---
# handlers file for ansible-gitea
- name: Restart gitea service
  ansible.builtin.service:
    name: gitea
    state: restarted

- name: Restart gitea socket
  ansible.builtin.service:
    name: gitea.main.socket
    state: restarted

- name: Restart postgresql service
  ansible.builtin.service:
    name: postgresql
    state: restarted
