---
# handlers file for ansible-gitea
- name: Restart gitea socket
  ansible.builtin.systemd:
    name: gitea.main.socket
    state: restarted
    daemon_reload: true

- name: Restart gitea service
  ansible.builtin.systemd:
    name: gitea
    state: restarted
    daemon_reload: true
